# Generated by Gemini

.PHONY: all install build run watch test clean fmt coverage

all: build

install:
	@echo "Installing dependencies..."
	@opam install . --deps-only --with-test --with-doc --with-dev-setup
	@cd example && npm install

build:
	@echo "Building project..."
	@cd example && npm run build
	@dune build

run:
	@echo "Running example app..."
	@dune exec ./example/src/bin/main.exe

watch:
	@echo "Running example app in watch mode..."
	@dune exec ./example/src/bin/main.exe --watch

test:
	@echo "Running tests..."
	@dune test

clean:
	@echo "Cleaning up..."
	@dune clean
	@rm -rf example/dist
	@rm -rf example/node_modules

fmt:
	@echo "Formatting code..."
	@dune fmt --auto-promote

coverage:
	@echo "Generating coverage report"
	@dune runtest --instrument-with bisect_ppx --force
	@bisect-ppx-report html
	@open _coverage/index.html

