name: CI

on:
  pull_request:
  push:

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - ocaml-base-compiler.4.12.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: ${{ matrix.os != 'macos-latest' }}
          opam-depext-flags: --with-test

      - run: opam pin add dream https://github.com/aantron/dream.git --dev-repo
      - run: opam install . --deps-only --with-test

      - run: cd example; npm install
      - run: cd example; npm run dev-build

      - run: opam exec -- dune build

      - run: opam exec -- dune test --force

